In [1]:
import numpy as np

In [8]:
# Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10
a=np.arange(2,11)
ar=a.reshape(3,3)
ar

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [4]:
# Write a NumPy program to get the unique elements of an array
c=np.array([10,20,20,30,40,50,40])
u=np.unique(c)
u

array([10, 20, 30, 40, 50])

In [9]:
# Write a NumPy program to find the union of two arrays. Union will return the
# unique, sorted array of values that are in either of the two input arrays.

a=np.array([10,20,20,30,40,50,40])
b=np.array([10,20,20,30,40,50,40])
union=np.union1d(a,b)
union

array([10, 20, 30, 40, 50])

In [18]:
# Write a NumPy program to create a 2-dimensional array of size 2 x 3
#  (composed of 4-byte integer elements), also print the shape, type and data
# type of the array.
a=np.array([[2, 4, 6], [6, 8, 10]])
sh=np.shape(a)
print('Shape:',sh)
print('Type:',a.dtype)

Shape: (2, 3)
Type: int32


In [21]:
# Write a NumPy program to create a 2D array whose diagonal equals [4, 5, 6,8] and 0's elsewhere.
a=np.zeros((4,4))
a[[0,1,2,3],[0,1,2,3]]=[4,5,6,8]
a

array([[4., 0., 0., 0.],
       [0., 5., 0., 0.],
       [0., 0., 6., 0.],
       [0., 0., 0., 8.]])

In [23]:
# Write a NumPy program to create a null vector of size 6 (1D) and update sixth value to 9
a=np.zeros(10)
a[5]=9
a

array([0., 0., 0., 0., 0., 9., 0., 0., 0., 0.])

In [24]:
# Write a NumPy program to create a array with values ranging from 12 to 39
a=np.arange(12,40)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [27]:
# Write a NumPy program to reverse a 1D array (first element becomes last).
a=np.array([1,2,3,4,5])
rev=np.flip(a)
rev

array([5, 4, 3, 2, 1])

In [41]:
# Write a NumPy program to an array converted to a float type
a=np.array(['1','2','3'])
print(a)
print('Original Array:',str(type(a[0])))
arr=a.astype(float)
print(arr)
print('Converted Array:',str(type(arr[0])))

['1' '2' '3']
Original Array: <class 'numpy.str_'>
[1. 2. 3.]
Converted Array: <class 'numpy.float64'>


In [48]:
# Write a NumPy program to create a 8x8 matrix and fill it with a checkerboard pattern
a=np.zeros([8,8])
a[0::2,0::2]=1
a[1::2,1::2]=1
print(a)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


In [53]:
# Write a NumPy program to convert the values of Centigrade degrees into
# Fahrenheit degrees. Centigrade values are stored into a NumPy array

c=np.array([0,65,48,69,48])
print("Values in  Fahrenheit:")
print(np.round((9*c/5 + 32)))

Values in  Fahrenheit:
[ 32. 149. 118. 156. 118.]


In [56]:
# Write a NumPy program to find the number of elements of an array, length of
# one array element in bytes and total bytes consumed by the elements.
c=np.array([1,10,5,30,7])
print('No of Elements:',c.size)
print('Length of one array element in bytes:',c.itemsize)
print('Total bytes consumed by the elements:',c.nbytes)

No of Elements: 5
Length of one array element in bytes: 4
Total bytes consumed by the elements: 20


In [58]:
# Write a NumPy program to test whether each element of a 1-D array is also present in a second array
a=np.array([1,2,3,4,5])
b=np.array([1,2,3,4,5,6])
print(np.in1d(a,b))

[ True  True  True  True  True]


In [60]:
# Write a NumPy program to find common values between two arrays
a=np.array([1,2,3,4,5])
b=np.array([1,2,3,4,5,6])
print('Common Values:',np.intersect1d(a,b))

Common Values: [1 2 3 4 5]


In [68]:
# Write a NumPy program to remove specific elements in a numpy array.
# Original array:
# [ 10 20 30 40 50 60 70 80 90 100]
# Delete first, fourth and fifth elements:
# [ 20 30 60 70 80 90 100]

a=np.array([[ 10 ,20, 30, 40, 50, 60, 70, 80, 90, 100]])
index=[0,4,5]
na=np.delete(a,index)
na

array([ 20,  30,  40,  70,  80,  90, 100])

In [70]:
# Write a NumPy program to replace the negative values in a numpy array with 0. [-1 -4 0 2 3 4 5 -6]
a=np.array([[-1 ,-4 ,0 ,2 ,3 ,4 ,5 ,-6]])
a[a<0]=0
a

array([[0, 0, 0, 2, 3, 4, 5, 0]])

In [72]:
# Write a NumPy program to count the occurrence of a specified item in a given NumPy array.
# [10 20 20 20 20 0 20 30 30 30 0 0 20 20 0] find the occurence of 20

a=np.array([[10 ,20 ,20 ,20 ,20 ,0 ,20 ,30 ,30 ,30 ,0 ,0 ,20 ,20 ,0]])
print("Count of 20:",np.count_nonzero(a==20))

Count of 20: 7
