In [2]:
import numpy as np


In [2]:
a=np.array([1,2,3.5])
b=np.array((1,2,3))
print(a)
print(b)
           


[1.  2.  3.5]
[1 2 3]


In [3]:
type(a)

numpy.ndarray

In [4]:
a.dtype

dtype('float64')

In [5]:
# Indexing
print(a[0])
print(a[0:])
print(a[0:3])
print(a[1:3])


1.0
[1.  2.  3.5]
[1.  2.  3.5]
[2.  3.5]


In [6]:
# 2D Array
c=np.array([[1,2,3,4],[5,6,7,8]])
print(c)

[[1 2 3 4]
 [5 6 7 8]]


In [7]:
print(c[0])


[1 2 3 4]


In [8]:
print(c[0:])

[[1 2 3 4]
 [5 6 7 8]]


In [9]:
print(c[0,2:])

[3 4]


In [10]:
print(c[0][0])

1


In [11]:
# Example
d=np.array([[3,7,-5,0],[8,2,1,3],[7,-2,9,6]])
print(d)

[[ 3  7 -5  0]
 [ 8  2  1  3]
 [ 7 -2  9  6]]


In [12]:
print(d[0:,3])

[0 3 6]


In [13]:
print(d[1:,1:3])

[[ 2  1]
 [-2  9]]


In [14]:
print(d[1,2:])

[1 3]


In [15]:
print(d[1:,2])

[1 9]


## Array Initialization 

In [16]:
a=np.zeros((4,4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [17]:
b=np.ones((5,5))
print(b)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [18]:
a=np.full((4,4),'*')
print(a)

[['*' '*' '*' '*']
 ['*' '*' '*' '*']
 ['*' '*' '*' '*']
 ['*' '*' '*' '*']]


In [19]:
# Generate seq of integers
a=np.arange(1,10,2)
print(a)

[1 3 5 7 9]


In [20]:
a=np.arange(10,0,-2)
print(a)

[10  8  6  4  2]


In [21]:
arr=np.zeros((4,4))
arr[[0,1,2,3],[0,1,2,3]]=1
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [22]:
# Generate equally spaced values
# (start,end,no of elements )
a=np.linspace(1,11,10)
a

array([ 1.        ,  2.11111111,  3.22222222,  4.33333333,  5.44444444,
        6.55555556,  7.66666667,  8.77777778,  9.88888889, 11.        ])

In [23]:
# Random-generate b/w 0 and 1
a=np.random.random(10)
a

array([0.87822061, 0.48982051, 0.93672184, 0.82363268, 0.55534247,
       0.49155883, 0.27281832, 0.95007271, 0.23794979, 0.58243832])

In [24]:
# Rand INT -generate int values between  start and end
a=np.random.randint(1,10,10)
a

array([8, 6, 3, 1, 1, 6, 3, 4, 8, 4])

In [25]:
# Generate a 2d array of random no's
# (start,end,(row,col))
a=np.random.randint(1,10,(4,4))
a

array([[6, 1, 3, 9],
       [1, 9, 4, 4],
       [2, 5, 8, 8],
       [1, 3, 2, 2]])

In [26]:
a.shape

(4, 4)

In [27]:
a.size

16

In [28]:
# size of each ele in bytes
a.itemsize

4

In [29]:
# size of array in bytes
a.nbytes

64

In [30]:
# Dimension of array
a.ndim

2

In [31]:
a=np.random.random(10)
# a
a.shape
a.ndim
a.itemsize


8

In [32]:
# change datatype
x=a.astype('float')
x

array([0.05714466, 0.85936696, 0.90776597, 0.05387715, 0.51829235,
       0.47676468, 0.91356864, 0.78686413, 0.49758595, 0.3149463 ])

In [33]:
x.dtype


dtype('float64')

In [34]:
arr=np.array([2,10,7,8])
# Append to an array
np.append(arr,6)

array([ 2, 10,  7,  8,  6])

In [35]:
d=np.array([[3,7,-5,0],[8,2,1,3],[7,-2,9,6]])
np.append(d,10)

array([ 3,  7, -5,  0,  8,  2,  1,  3,  7, -2,  9,  6, 10])

In [36]:
np.append(d,(1,2,3))

array([ 3,  7, -5,  0,  8,  2,  1,  3,  7, -2,  9,  6,  1,  2,  3])

In [37]:
np.insert(arr,2,8)

array([ 2, 10,  8,  7,  8])

In [38]:
d=np.array([[3,7,-5,0],[8,2,1,3],[7,-2,9,6]])
np.insert(d,2,0)

array([ 3,  7,  0, -5,  0,  8,  2,  1,  3,  7, -2,  9,  6])

In [39]:
d=np.array([[3,7,0],[8,2,3],[7,9,6]])
# (array name,position,value,axis=0/1)
# axis 0:row
# axis 1:column
np.insert(d,2,3,axis=0)

array([[3, 7, 0],
       [8, 2, 3],
       [3, 3, 3],
       [7, 9, 6]])

In [40]:
np.insert(d,2,3,axis=1)

array([[3, 7, 3, 0],
       [8, 2, 3, 3],
       [7, 9, 3, 6]])

In [41]:
# to insert seq of values to array
np.insert(d,2,[1,1,1],axis=0)


array([[3, 7, 0],
       [8, 2, 3],
       [1, 1, 1],
       [7, 9, 6]])

In [42]:
# delete element from array
# (array name,posn)
s=np.delete(d,3)
s

array([3, 7, 0, 2, 3, 7, 9, 6])

In [43]:
s

array([3, 7, 0, 2, 3, 7, 9, 6])

In [44]:
d=np.array([[3,7,0],[8,2,3],[7,9,6]])
d
# delete a row/col
np.delete(d,1,axis=0)

array([[3, 7, 0],
       [7, 9, 6]])

In [45]:
d=np.array([[3,7,0],[8,2,3],[7,9,6]])
d
# (arrayname,row/col indices to delete,axis)
np.delete(d,(0,1),axis=0)

array([[7, 9, 6]])

In [46]:
# create copy of array
d=np.array([[3,7,0],[8,2,3],[7,9,6]])
v=d.copy()
v

array([[3, 7, 0],
       [8, 2, 3],
       [7, 9, 6]])

In [47]:
a=np.array([4,2,8])
a
# Sort an array(ascending)
sorted=np.sort(a)
sorted

array([2, 4, 8])

In [48]:
# descending sort
np.sort(a)[::-1]

array([8, 4, 2])

In [49]:
a.sort()
a

array([2, 4, 8])

In [50]:
a[::-1].sort()
a

array([8, 4, 2])

## Stacking Arrays


In [51]:
arr1=np.array([[3,9,8],[6,5,7],[3,9,8]])
arr2=np.array([[3,9,8],[2,6,7],[3,5,7]])
arr3=np.array([[2,6,7],[6,5,7],[6,5,7]])

In [52]:
arr1

array([[3, 9, 8],
       [6, 5, 7],
       [3, 9, 8]])

In [53]:
# Vertical Stacking
np.vstack([arr1,arr2])

array([[3, 9, 8],
       [6, 5, 7],
       [3, 9, 8],
       [3, 9, 8],
       [2, 6, 7],
       [3, 5, 7]])

In [54]:
# same as vstack(0=row)
np.concatenate([arr1,arr2],axis=0)  

array([[3, 9, 8],
       [6, 5, 7],
       [3, 9, 8],
       [3, 9, 8],
       [2, 6, 7],
       [3, 5, 7]])

In [55]:
# Horizontal Stacking
np.hstack([arr1,arr2])

array([[3, 9, 8, 3, 9, 8],
       [6, 5, 7, 2, 6, 7],
       [3, 9, 8, 3, 5, 7]])

In [56]:
np.concatenate([arr1,arr2],axis=1)


array([[3, 9, 8, 3, 9, 8],
       [6, 5, 7, 2, 6, 7],
       [3, 9, 8, 3, 5, 7]])

In [57]:
# To convert to a single dimensional array
arr1.ravel()

array([3, 9, 8, 6, 5, 7, 3, 9, 8])

In [3]:
# SLICING
arr1=np.array([[3,9,8,6],[1,6,5,7],[6,3,9,8]])
arr1
# ([ROW],[COLS])
print(arr1[[2,1,2],[0,1,3]])

[6 6 8]


In [59]:
arr1=np.array([[3,9,8,6,7],[1,6,5,7,5],[6,3,9,8,3],[1,6,5,7,5]])
arr1
print(arr1[1::2,:])

[[1 6 5 7 5]
 [1 6 5 7 5]]


In [60]:
arr1

array([[3, 9, 8, 6, 7],
       [1, 6, 5, 7, 5],
       [6, 3, 9, 8, 3],
       [1, 6, 5, 7, 5]])

In [61]:
arr1=np.array([[3,4,-1,0,8],[3,5,7,6,2],[-1,0,9,4,8],[6,7,-2,0,1]])
arr1

array([[ 3,  4, -1,  0,  8],
       [ 3,  5,  7,  6,  2],
       [-1,  0,  9,  4,  8],
       [ 6,  7, -2,  0,  1]])

In [62]:
print(arr1[1::2,0::2])

[[ 3  7  2]
 [ 6 -2  1]]


In [63]:
q=np.zeros([8,8])
q

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [64]:

q

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [65]:
q[0::2,0::2]=1
print(q)


[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [66]:
q[1::2,1::2]=1
print(q)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


## Matrix Multiplication

In [67]:
arr1=np.array([[3,9,8],[1,6,5],[6,3,9]])
arr1=np.array([[3,9,8],[6,3,9],[1,6,5]])

# ELEMENT WISE MULTIPLICATION
arr1*arr2

array([[ 9, 81, 64],
       [12, 18, 63],
       [ 3, 30, 35]])

In [68]:
# Matrix Multiplication
np.matmul(arr1,arr2)

array([[ 51, 121, 143],
       [ 51, 117, 132],
       [ 30,  70,  85]])

In [69]:
a=np.ones((2,3))
b=np.full((3,2),5)
c=np.full((2,3),5)

In [70]:
np.matmul(a,b)

array([[15., 15.],
       [15., 15.]])

In [71]:
np.matmul(b,a)

array([[10., 10., 10.],
       [10., 10., 10.],
       [10., 10., 10.]])

In [72]:
arr1

array([[3, 9, 8],
       [6, 3, 9],
       [1, 6, 5]])

In [73]:
# Find the max value in array
np.max(arr1)

9

In [74]:
# Find the min value in array
np.min(arr1)

1

In [75]:
np.max(arr1,axis=0)

array([6, 9, 9])

In [76]:
np.max(arr1,axis=1)

array([9, 9, 6])

In [77]:
np.sum(arr1)

50

In [78]:
np.sum([5,5,1])

11

## Loading Text Files

In [79]:
import os
# Get current working directory 
os.getcwd()

'C:\\Users\\Amjad\\Documents\\Python Class DA\\Machine Learning\\Numpy'

In [80]:
data=np.genfromtxt('abc.txt',delimiter=',')
data

array([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [4., 5., 6., 7., 7., 8., 3., 5., 3.],
       [2., 3., 5., 6., 4., 3., 2., 1., 4.],
       [2., 4., 5., 3., 5., 3., 5., 3., 5.]])

In [96]:
data=np.genfromtxt(r'C:\Users\Amjad\Documents\Python Class DA\Machine Learning\Numpy\abc.txt',delimiter=',')
data

array([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [4., 5., 6., 7., 7., 8., 3., 5., 3.],
       [2., 3., 5., 6., 4., 3., 2., 1., 4.],
       [2., 4., 5., 3., 5., 3., 5., 3., 5.]])

## Boolean Masking

In [88]:
data>5

array([[False, False, False, False, False,  True,  True,  True,  True],
       [False, False,  True,  True,  True,  True, False, False, False],
       [False, False, False,  True, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False]])

In [89]:
data==5

array([[False, False, False, False,  True, False, False, False, False],
       [False,  True, False, False, False, False, False,  True, False],
       [False, False,  True, False, False, False, False, False, False],
       [False, False,  True, False,  True, False,  True, False,  True]])

In [90]:
data>=5

array([[False, False, False, False,  True,  True,  True,  True,  True],
       [False,  True,  True,  True,  True,  True, False,  True, False],
       [False, False,  True,  True, False, False, False, False, False],
       [False, False,  True, False,  True, False,  True, False,  True]])

In [97]:
np.any(data>5, axis=1)

array([ True,  True,  True, False])

In [98]:
np.all(data>5,axis=1)

array([False, False, False, False])

### Conditional selection 

In [99]:
data[data>5]

array([6., 7., 8., 9., 6., 7., 7., 8., 6.])

In [100]:
data[((data>5) & (data>8))]

array([9.])

In [101]:
data[data%2==0]

array([2., 4., 6., 8., 4., 6., 8., 2., 6., 4., 2., 4., 2., 4.])

In [104]:
new=np.array([[1,2,3],[4,5,6],[7,8,9]])
new

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [106]:
# np.split(aray name,no of splits,axis)
np.split(new,3,axis=1)

[array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]]),
 array([[3],
        [6],
        [9]])]

In [107]:
# np.split(arr,[a,b],axis=0/1)  ---arr[:a],arr[a:b],arr[b:]
np.split(new,[1,3],axis=0)  #[:1],[1:3].[3:]

[array([[1, 2, 3]]),
 array([[4, 5, 6],
        [7, 8, 9]]),
 array([], shape=(0, 3), dtype=int32)]

In [108]:
np.split(new,[1,2],axis=0)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

### Comparing arrays

In [109]:
a=np.array([1,2,3])
b=np.array([2,4,3])

In [110]:
# Elemt wise comparison
np.equal(a,b)

array([False, False,  True])

In [111]:
# Comparing full array
np.array_equal(a,b)

False

In [116]:
# Array Broadcasting
a=np.array([[1,2,3],[2,3,8],[6,7,8]])
b=np.array([[3,2,1]])

In [119]:
np.sum([a,b])

array([[4, 4, 4],
       [5, 5, 9],
       [9, 9, 9]])

In [118]:
import warnings
warnings.filterwarnings('ignore')

In [120]:
a

array([[1, 2, 3],
       [2, 3, 8],
       [6, 7, 8]])