In [2]:
import numpy as np

In [5]:
new=np.array([[2,4,6,8],[1,3,5,7],[1,2,3,4]])
new

array([[2, 4, 6, 8],
       [1, 3, 5, 7],
       [1, 2, 3, 4]])

In [29]:
print(new[1:,1])
print(new[1:,2])
print(new[1:,3])
print(new[1:,0])

[3 2]
[5 3]
[7 4]
[1 1]


In [32]:
new=np.random.randint(10,20,(3,4)) 
new

array([[14, 19, 15, 18],
       [10, 16, 17, 19],
       [15, 18, 15, 14]])

In [33]:
new.size

12

In [34]:
new.itemsize

4

In [36]:
new.ndim

2

In [37]:
new.nbytes

48

In [38]:
new.shape

(3, 4)

In [39]:
new

array([[14, 19, 15, 18],
       [10, 16, 17, 19],
       [15, 18, 15, 14]])

In [41]:
np.append(new,16)

array([14, 19, 15, 18, 10, 16, 17, 19, 15, 18, 15, 14, 16])

In [44]:
np.append(new,(16,17,18))

array([14, 19, 15, 18, 10, 16, 17, 19, 15, 18, 15, 14, 16, 17, 18])

In [47]:
np.insert(new,1,20)

array([14, 20, 19, 15, 18, 10, 16, 17, 19, 15, 18, 15, 14])

In [48]:
np.insert(new,2,20,axis=1)

array([[14, 19, 20, 15, 18],
       [10, 16, 20, 17, 19],
       [15, 18, 20, 15, 14]])

In [46]:
np.insert(new,4,[16,17,18],axis=1)

array([[14, 19, 15, 18, 16],
       [10, 16, 17, 19, 17],
       [15, 18, 15, 14, 18]])

In [53]:
np.insert(new,3,[12,13,14,15],axis=0)

array([[14, 19, 15, 18],
       [10, 16, 17, 19],
       [15, 18, 15, 14],
       [12, 13, 14, 15]])

In [51]:
h=np.insert(new,3,[12,13,14,15],axis=0)
h

array([[14, 19, 15, 18],
       [10, 16, 17, 19],
       [15, 18, 15, 14],
       [12, 13, 14, 15]])

In [50]:
new

array([[14, 19, 15, 18],
       [10, 16, 17, 19],
       [15, 18, 15, 14]])

In [52]:
h

array([[14, 19, 15, 18],
       [10, 16, 17, 19],
       [15, 18, 15, 14],
       [12, 13, 14, 15]])

In [54]:
np.delete(h,3,axis=0)

array([[14, 19, 15, 18],
       [10, 16, 17, 19],
       [15, 18, 15, 14]])

In [55]:
np.delete(h,1,axis=1)

array([[14, 15, 18],
       [10, 17, 19],
       [15, 15, 14],
       [12, 14, 15]])

In [7]:
h

NameError: name 'h' is not defined

In [58]:
r=np.sort(h)
r

array([[14, 15, 18, 19],
       [10, 16, 17, 19],
       [14, 15, 15, 18],
       [12, 13, 14, 15]])

In [60]:
h[::-1].sort()

## EXERCISES  23-05-23

In [4]:
# 1
data=np.random.randint(2,10,(3,3))
data

array([[9, 2, 3],
       [2, 2, 5],
       [6, 7, 6]])

In [5]:
# 2
data1=np.unique(data)
data1

array([2, 3, 5, 6, 7, 9])

In [9]:
# 3
arr1=np.array([20,40,60,80])
arr2=np.array([10,30,50,70])

In [10]:
data2=np.union1d(arr1,arr2)
data2

array([10, 20, 30, 40, 50, 60, 70, 80])

In [11]:
# 4
arr=np.array([[20,40,60],[10,30,50]], np.int32)
arr

array([[20, 40, 60],
       [10, 30, 50]])

In [12]:
arr.shape

(2, 3)

In [15]:
arr.nbytes

24

In [16]:
arr.dtype

dtype('int32')

In [17]:
# 5
# diagonal equals

q=np.diagflat([4,5,6,8])
q


array([[4, 0, 0, 0],
       [0, 5, 0, 0],
       [0, 0, 6, 0],
       [0, 0, 0, 8]])

In [18]:
# 6
w=np.zeros(6)
w

array([0., 0., 0., 0., 0., 0.])

In [27]:
w[5]= 9
w

array([0., 0., 0., 0., 0., 9.])

In [37]:
# 7
e=np.arange(12,40,)
e

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [38]:
# 8
e=e[::-1]
e

array([39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23,
       22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12])

In [40]:
# 9
r=np.arange(11)
r

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
r.dtype

dtype('int32')

In [48]:
r=r.astype('float')
r

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [49]:
r.dtype

dtype('float64')

In [50]:
# 10

c=np.zeros([8,8])
c

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [51]:
c[0::2,0::2]=1
c

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [52]:
c[1::2,1::2]=1
c

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

In [53]:
# 11
arr3=np.random.randint(1,10,(4,5))
arr3

array([[4, 6, 8, 1, 4],
       [4, 5, 3, 4, 3],
       [7, 3, 8, 4, 7],
       [8, 1, 1, 2, 3]])

In [54]:
arr3.size

20

In [55]:
arr3.itemsize

4

In [56]:
arr3.nbytes

80

In [57]:
len(arr3)

4

In [3]:
# 
arr1=np.array([20,40,60,80])
arr2=np.array([10,30,50,70])

In [5]:
(np.in1d(arr1,arr2))

array([False, False, False, False])

In [6]:
# 
arr1=np.array([20,40,60,30])
arr2=np.array([10,30,50,40])

In [7]:
(np.intersect1d(arr1,arr2))

array([30, 40])

In [9]:
arr3=np.array([ 10,20,30, 40, 50, 60, 70, 80, 90 ,100])
arr3

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [ ]:
arr4=np.delete(arr3,1)