In [20]:
from sklearn.datasets import load_digits
from sklearn.model_selection import KFold, StratifiedKFold, cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC

In [5]:
# Example
fold = KFold(n_splits=5)

In [6]:
# example for KFold  (alll values are used for train and test)
list1= [1,3,5,6,1,8,9,5,6,7,9,10]
for train, test in fold.split(list1):
    print (train, test)

[ 3  4  5  6  7  8  9 10 11] [0 1 2]
[ 0  1  2  6  7  8  9 10 11] [3 4 5]
[ 0  1  2  3  4  5  8  9 10 11] [6 7]
[ 0  1  2  3  4  5  6  7 10 11] [8 9]
[0 1 2 3 4 5 6 7 8 9] [10 11]


In [7]:
fold = StratifiedKFold(n_splits=5)  #for keeping the splits balanced

In [8]:
digits= load_digits()

In [23]:
def get_score(model,x_train,x_test,y_train,y_test):
    model.fit(x_train,y_train)
    return model.score(x_test,y_test)

# lists for saving the scores of the model
log_score= []
svm_score= []
rf_score= []

for train_index, test_index in fold.split(digits.data, digits.target):
    x_train,x_test, y_train, y_test = digits.data[train_index], digits.data[test_index],digits.target[train_index],digits.target[test_index]
    log_score.append(get_score(LogisticRegression(), x_train,x_test,y_train,y_test))
    svm_score.append(get_score(SVC(),x_train,x_test,y_train,y_test))
    rf_score.append(get_score(RandomForestClassifier(random_state=34),x_train,x_test,y_train,y_test))

In [24]:
svm_score

[0.9611111111111111,
 0.9444444444444444,
 0.9832869080779945,
 0.9888579387186629,
 0.9387186629526463]

In [25]:
rf_score

[0.925,
 0.9111111111111111,
 0.958217270194986,
 0.9610027855153204,
 0.9275766016713092]

In [26]:
import numpy as np
print (np.mean(log_score))
print (np.mean(svm_score))
print (np.mean(rf_score))

0.9137650882079852
0.9632838130609718
0.9365815536985453


In [21]:
#to ignore warning messages
import warnings
warnings.filterwarnings('ignore')

In [27]:
# best easy method
log_score = cross_val_score(LogisticRegression(),X= digits.data, y= digits.target, cv=5) #default cv
svm_score = cross_val_score(SVC(), X=digits.data, y=digits.target)
rf_score = cross_val_score(RandomForestClassifier(random_state=12), X= digits.data, y=digits.target)

In [28]:
print(log_score)
print(svm_score)
print(rf_score)

[0.92222222 0.86944444 0.94150418 0.93871866 0.89693593]
[0.96111111 0.94444444 0.98328691 0.98885794 0.93871866]
[0.93611111 0.91111111 0.95264624 0.97771588 0.9275766 ]


In [29]:
print(log_score.mean())
print(svm_score.mean())
print(rf_score.mean())

0.9137650882079852
0.9632838130609718
0.9410321881770349
