In [6]:
import numpy as np

### creating a one-dimensional numpy array

In [9]:
a=np.array([2,3.4,7,8.3,1,3.0])
b=np.array((4,6,8,10,12))
print(a)
print(b)
b

[2.  3.4 7.  8.3 1.  3. ]
[ 4  6  8 10 12]


array([ 4,  6,  8, 10, 12])

In [10]:
type(a)

numpy.ndarray

In [15]:
b.dtype

dtype('int32')

In [14]:
a.dtype

dtype('float64')

In [19]:
# indexing
print(a[0])
print(a[0:])
print(a[:2])
print(a[1:3])

2.0
[2.  3.4 7.  8.3 1.  3. ]
[2.  3.4]
[3.4 7. ]


## 2 dimensional array

In [4]:
b=np.array([[1,2,3,4],[2,4,6,8]])
print(b)

[[1 2 3 4]
 [2 4 6 8]]


print(b[0])
print(b[0:])
print(b[1])
print(b[1][1])
print(b[0,2])
print(b[:2])
print(b[0,3])
print(b[1][3])

In [34]:
q=np.array([[3,7,-5,0],[8,2,1,3],[7,-2,9,6]])
print(q)

[[ 3  7 -5  0]
 [ 8  2  1  3]
 [ 7 -2  9  6]]


In [38]:
print(q[1:,1:3])


[[ 2  1]
 [-2  9]]


In [40]:
print(q[1,2:])

[1 3]


In [41]:
print(q[0:,3])

[0 3 6]


In [42]:
print(q[1:,2])

[1 9]


## array initialization

In [43]:
# creating an array full of zeros
a=np.zeros((3,2))
a

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [44]:
a.dtype

dtype('float64')

In [45]:
# creating an array full of ones
b=np.ones((4,4))
b

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [47]:
b.dtype

dtype('float64')

In [50]:
# array_name= np.full((rows, columns), default_value)
c=np.full((3,4),'zz')
c

array([['zz', 'zz', 'zz', 'zz'],
       ['zz', 'zz', 'zz', 'zz'],
       ['zz', 'zz', 'zz', 'zz']], dtype='<U2')

In [54]:
# generate a sequence of integers
# array_name = np.arange(start,stop,step)
a=np.arange(10,0,-2)
a

array([10,  8,  6,  4,  2])

In [56]:
arr1=np.zeros((4,4))
arr1[[0,1,2,3],[0,1,2,3]]=1
arr1

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [6]:
import numpy as np

## 15-5-23

In [5]:
# GENERTES A SEQUENCE OF EQUALLY SPACED VALUES AND END     only 1 to 10

# array_name = np.linspace(start,end,no of elements)

a =np.linspace(5,10,20)
a

array([ 5.        ,  5.26315789,  5.52631579,  5.78947368,  6.05263158,
        6.31578947,  6.57894737,  6.84210526,  7.10526316,  7.36842105,
        7.63157895,  7.89473684,  8.15789474,  8.42105263,  8.68421053,
        8.94736842,  9.21052632,  9.47368421,  9.73684211, 10.        ])

In [53]:
a.ndim

1

## Random Module

In [9]:
# Generate random values between 0 and 1
# array_name= np.random.random(no of elements)

arr1= np.random.random(10)
arr1

array([0.56641557, 0.68430492, 0.50638357, 0.39872694, 0.19122562,
       0.36911902, 0.38268985, 0.26264452, 0.6108355 , 0.27986989])

### 1D

In [10]:
# generate a 1D array of random integer values between 'star'(inclusive) and 'end'(exclusive) 
# array_name = np.random.randint(start,end,no of elements)
arr2= np.random.randint(1,10,15)
arr2

array([9, 1, 7, 6, 7, 6, 6, 3, 9, 3, 2, 5, 2, 1, 7])

### 2D

In [13]:
# GENERATES a 2D arry of random integers

#array_name= np.random.randint(start,end,(row ,col))

arr3=np.random.randint(1,10,(4,5))
arr3

array([[4, 9, 2, 7, 9],
       [8, 3, 4, 6, 7],
       [2, 7, 1, 4, 4],
       [6, 9, 6, 5, 1]])

In [14]:
arr3.shape  # no of rows and columns

(4, 5)

In [15]:
arr3.size   # total no of elemets of the array

20

In [16]:
arr3.itemsize # size of each elements in bytes

4

In [17]:
arr3.nbytes   #total size of the array in bytes

80

In [18]:
arr3.ndim    # dimension of the array

2

In [20]:
ar= np.random.randint(2,10,(4,3))
ar

array([[3, 6, 9],
       [4, 3, 6],
       [8, 7, 6],
       [4, 9, 2]])

In [21]:
ar.shape

(4, 3)

In [22]:
ar.size

12

In [23]:
ar.itemsize

4

In [24]:
ar.nbytes

48

In [25]:
ar.ndim

2

In [31]:
d=np.full((3,3),4)
d

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

## Changing type of array

In [33]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
a.dtype

dtype('int32')

In [37]:
# astype

a=a.astype('float')
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [38]:
a.dtype

dtype('float64')

## ADD or REMOVE elements

In [45]:
arr=np.array([2,10,7,8])

# insert values to the end of the array
# np.append(array_name,value)

np.append(arr,6)

array([ 2, 10,  7,  8,  6])

In [46]:
arr3

array([[4, 9, 2, 7, 9],
       [8, 3, 4, 6, 7],
       [2, 7, 1, 4, 4],
       [6, 9, 6, 5, 1]])

In [48]:
np.append(arr3,10)

array([ 4,  9,  2,  7,  9,  8,  3,  4,  6,  7,  2,  7,  1,  4,  4,  6,  9,
        6,  5,  1, 10])

In [49]:
np.append(arr3,(5,10,15))

array([ 4,  9,  2,  7,  9,  8,  3,  4,  6,  7,  2,  7,  1,  4,  4,  6,  9,
        6,  5,  1,  5, 10, 15])

In [50]:
# insertn element at a particular position
# np.insert(array_name,position,element)

np.insert(arr,2,3)

array([ 2, 10,  3,  7,  8])

In [51]:
ar

array([[3, 6, 9],
       [4, 3, 6],
       [8, 7, 6],
       [4, 9, 2]])

In [52]:
np.insert(ar,2,10)

array([ 3,  6, 10,  9,  4,  3,  6,  8,  7,  6,  4,  9,  2])

In [54]:
# np.insert(array_name,position,value,axis=0/1)
# axis 0: row
# axis 1: column

np.insert(arr3,2,3, axis=0)

array([[4, 9, 2, 7, 9],
       [8, 3, 4, 6, 7],
       [3, 3, 3, 3, 3],
       [2, 7, 1, 4, 4],
       [6, 9, 6, 5, 1]])

In [57]:
np.insert(arr3,1,10, axis=1)

array([[ 4, 10,  9,  2,  7,  9],
       [ 8, 10,  3,  4,  6,  7],
       [ 2, 10,  7,  1,  4,  4],
       [ 6, 10,  9,  6,  5,  1]])

In [59]:
# to give multiple diferent numbers

np.insert(arr3,1,[1,2,3,4,5],axis=0)

array([[4, 9, 2, 7, 9],
       [1, 2, 3, 4, 5],
       [8, 3, 4, 6, 7],
       [2, 7, 1, 4, 4],
       [6, 9, 6, 5, 1]])

In [61]:
np.insert(arr3,2,[1,2,3,4,], axis=1)

array([[4, 9, 1, 2, 7, 9],
       [8, 3, 2, 4, 6, 7],
       [2, 7, 3, 1, 4, 4],
       [6, 9, 4, 6, 5, 1]])

In [62]:
arr5 =np.random.randint(1,10,(3,2))
arr5

array([[5, 8],
       [3, 7],
       [1, 1]])

In [63]:
# delete element from an array

#  np.delete(array_name,position)
t=np.delete(arr5,4)
arr5

array([[5, 8],
       [3, 7],
       [1, 1]])

In [65]:
t

array([5, 8, 3, 7, 1])

In [67]:
arr3

array([[4, 9, 2, 7, 9],
       [8, 3, 4, 6, 7],
       [2, 7, 1, 4, 4],
       [6, 9, 6, 5, 1]])

In [68]:
# np.delete(array_name,position,row/col)

np.delete(arr3,1,axis=1)

array([[4, 2, 7, 9],
       [8, 4, 6, 7],
       [2, 1, 4, 4],
       [6, 6, 5, 1]])

In [69]:
np.delete(arr3,2,axis=0)

array([[4, 9, 2, 7, 9],
       [8, 3, 4, 6, 7],
       [6, 9, 6, 5, 1]])

In [70]:
# np.delete(array_name, (tuple of row/column indices to delete), axis=0/1)
# drelete multiple rows and column

np.delete(arr3,(1,0),axis=1)

array([[2, 7, 9],
       [4, 6, 7],
       [1, 4, 4],
       [6, 5, 1]])

In [72]:
np.delete(arr3,(1,2), axis=0)

array([[4, 9, 2, 7, 9],
       [6, 9, 6, 5, 1]])

In [76]:
a=np.array([3,2,7])
b=np.copy(a)

In [77]:
b

array([3, 2, 7])

In [78]:
# creates a copy of  an array
b=a.copy()

In [79]:
b

array([3, 2, 7])

In [80]:
# returns a new sorted array-ascending
a=np.array([4,2,8])
sorted_a= np.sort(a)     # USING sort() as a Function 
sorted_a

array([2, 4, 8])

In [81]:
a    # a dont change with the abouve operation. A new array is created

array([4, 2, 8])

In [82]:
# descending sorting 

np.sort(a)[::-1]

array([8, 4, 2])

In [83]:
a

array([4, 2, 8])

In [84]:
a.sort()   # sort() as method

In [85]:
a

array([2, 4, 8])

In [87]:
a[::-1].sort()   #this chamges 'a' -- using sort() as a method
a

array([8, 4, 2])

## 16-05-23

## stacking of arrays

In [19]:
import numpy as np

In [4]:
arr1=np.array([[1,2,3],[7,8,9],[4,5,6]])
arr2=np.array([[4,7,-9],[2,4,6],[9,8,-7]])
arr3=np.array([[3,2,1],[6,5,4],[0,1,0]])

In [5]:
arr1

array([[1, 2, 3],
       [7, 8, 9],
       [4, 5, 6]])

In [6]:
arr2

array([[ 4,  7, -9],
       [ 2,  4,  6],
       [ 9,  8, -7]])

In [7]:
arr3

array([[3, 2, 1],
       [6, 5, 4],
       [0, 1, 0]])

In [9]:
# vertikle stacking
np.vstack([arr1,arr2,arr3])

array([[ 1,  2,  3],
       [ 7,  8,  9],
       [ 4,  5,  6],
       [ 4,  7, -9],
       [ 2,  4,  6],
       [ 9,  8, -7],
       [ 3,  2,  1],
       [ 6,  5,  4],
       [ 0,  1,  0]])

In [10]:
# same as vstack

np.concatenate([arr1,arr2],axis=0)


array([[ 1,  2,  3],
       [ 7,  8,  9],
       [ 4,  5,  6],
       [ 4,  7, -9],
       [ 2,  4,  6],
       [ 9,  8, -7]])

In [13]:
np.concatenate([arr1,arr2,arr3],axis=0)

array([[ 1,  2,  3],
       [ 7,  8,  9],
       [ 4,  5,  6],
       [ 4,  7, -9],
       [ 2,  4,  6],
       [ 9,  8, -7],
       [ 3,  2,  1],
       [ 6,  5,  4],
       [ 0,  1,  0]])

In [11]:
# horizontal stacking
np.hstack([arr1,arr2])

array([[ 1,  2,  3,  4,  7, -9],
       [ 7,  8,  9,  2,  4,  6],
       [ 4,  5,  6,  9,  8, -7]])

In [12]:
np.hstack([arr1,arr2,arr3])

array([[ 1,  2,  3,  4,  7, -9,  3,  2,  1],
       [ 7,  8,  9,  2,  4,  6,  6,  5,  4],
       [ 4,  5,  6,  9,  8, -7,  0,  1,  0]])

In [14]:
# to convert to single dimensional array
arr1.ravel()

array([1, 2, 3, 7, 8, 9, 4, 5, 6])

### numpy slicing

In [15]:
# arr[row,col]
# arr[start:stop:step,  start:stop:step]


In [16]:
arr9=np.array([[2,1,2,1],[4,5,3,0],[9,8,1,1]])
arr9

array([[2, 1, 2, 1],
       [4, 5, 3, 0],
       [9, 8, 1, 1]])

In [23]:
arr[[row],[col]]

arr9[[1,2,2],[2,0,3]]   #selecting random numbers 1st,select random number rows and 2nd, select random number column

array([3, 9, 1])

In [24]:
arr1=np.array([[2,1,2,1],[4,5,3,0],[9,8,1,1],[6,4,2,2]])
arr1

array([[2, 1, 2, 1],
       [4, 5, 3, 0],
       [9, 8, 1, 1],
       [6, 4, 2, 2]])

In [25]:
arr1[1::2,:]

array([[4, 5, 3, 0],
       [6, 4, 2, 2]])

In [29]:
arr1[2:3,:]

array([[9, 8, 1, 1]])

In [31]:
arr1=np.array([[3,4,-1,0,8],[3,5,7,6,2],[-1,0,9,4,8],[6,7,-2,0,1]])
arr1

array([[ 3,  4, -1,  0,  8],
       [ 3,  5,  7,  6,  2],
       [-1,  0,  9,  4,  8],
       [ 6,  7, -2,  0,  1]])

In [33]:
arr1[1::2,0::2]

array([[ 3,  7,  2],
       [ 6, -2,  1]])

#### chess board

In [45]:
c=np.zeros([8,8])
c

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [46]:
c[0::2,0::2]=1
c

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [48]:
c[1::2,1::2]=1
c

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

In [50]:
x=c.astype('int')
x

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

## array arithmetic operations

In [53]:
arr3

array([[3, 2, 1],
       [6, 5, 4],
       [0, 1, 0]])

In [55]:
arr2

array([[ 4,  7, -9],
       [ 2,  4,  6],
       [ 9,  8, -7]])

In [57]:
# element wise multiplication             should match row and col bt arrays

arr3*arr2


array([[12, 14, -9],
       [12, 20, 24],
       [ 0,  8,  0]])

In [58]:
# matrix multiplication
# row count and col count must be match
np.matmul(arr3,arr2)


array([[ 25,  37, -22],
       [ 70,  94, -52],
       [  2,   4,   6]])

In [59]:
a=np.ones((2,3))
b=np.full((3,2),5)
c=np.full((2,3),5)

In [60]:
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [61]:
b

array([[5, 5],
       [5, 5],
       [5, 5]])

In [62]:
c

array([[5, 5, 5],
       [5, 5, 5]])

In [63]:
np.matmul(a,b)

array([[15., 15.],
       [15., 15.]])

In [65]:
np.matmul(b,c)

array([[50, 50, 50],
       [50, 50, 50],
       [50, 50, 50]])

In [66]:
np.matmul(b,a)

array([[10., 10., 10.],
       [10., 10., 10.],
       [10., 10., 10.]])

In [67]:
arr1

array([[ 3,  4, -1,  0,  8],
       [ 3,  5,  7,  6,  2],
       [-1,  0,  9,  4,  8],
       [ 6,  7, -2,  0,  1]])

In [68]:
np.max(arr1)

9

In [69]:
np.min(arr1)

-2

In [70]:
np.max(arr1,axis=0)

array([6, 7, 9, 6, 8])

In [71]:
np.min(arr1,axis=1)

array([-1,  2, -1, -2])

In [73]:
np.sum([2,4,6])

12

In [74]:
np.sum(arr1)

69

In [17]:
arr1

5

## Loading Text Files

In [76]:
# get current working directory
import os
os.getcwd()   

"C:\\Users\\SHIBIN's\\ML_Libraries\\Numpy"

In [88]:
data= np.genfromtxt(r"C:\Users\SHIBIN's\Downloads\abc.txt", delimiter=',')
data                  

array([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [4., 5., 6., 7., 7., 8., 3., 5., 3.],
       [2., 3., 5., 6., 4., 3., 2., 1., 4.],
       [2., 4., 5., 3., 5., 3., 5., 3., 5.]])

In [14]:
data=np.genfromtxt('abc.txt',delimiter=',')
data

array([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [4., 5., 6., 7., 7., 8., 3., 5., 3.],
       [2., 3., 5., 6., 4., 3., 2., 1., 4.],
       [2., 4., 5., 3., 5., 3., 5., 3., 5.]])

## 22-05-23

## boolean masking

In [2]:
import numpy as np

In [16]:
data>5

array([[False, False, False, False, False,  True,  True,  True,  True],
       [False, False,  True,  True,  True,  True, False, False, False],
       [False, False, False,  True, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False]])

In [18]:
data>=5

array([[False, False, False, False,  True,  True,  True,  True,  True],
       [False,  True,  True,  True,  True,  True, False,  True, False],
       [False, False,  True,  True, False, False, False, False, False],
       [False, False,  True, False,  True, False,  True, False,  True]])

In [19]:
data==5

array([[False, False, False, False,  True, False, False, False, False],
       [False,  True, False, False, False, False, False,  True, False],
       [False, False,  True, False, False, False, False, False, False],
       [False, False,  True, False,  True, False,  True, False,  True]])

In [20]:
data<=5

array([[ True,  True,  True,  True,  True, False, False, False, False],
       [ True,  True, False, False, False, False,  True,  True,  True],
       [ True,  True,  True, False,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True]])

In [21]:
np.all(data>5, axis=1)

array([False, False, False, False])

In [22]:
data

array([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [4., 5., 6., 7., 7., 8., 3., 5., 3.],
       [2., 3., 5., 6., 4., 3., 2., 1., 4.],
       [2., 4., 5., 3., 5., 3., 5., 3., 5.]])

In [23]:
np.any(data>5, axis=1)

array([ True,  True,  True, False])

### conditional selection

In [25]:
data

array([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [4., 5., 6., 7., 7., 8., 3., 5., 3.],
       [2., 3., 5., 6., 4., 3., 2., 1., 4.],
       [2., 4., 5., 3., 5., 3., 5., 3., 5.]])

In [26]:
data[data>5]

array([6., 7., 8., 9., 6., 7., 7., 8., 6.])

In [28]:
data[((data>5) & (data<8))]

array([6., 7., 6., 7., 7., 6.])

In [32]:
data[data%2==0]

array([2., 4., 6., 8., 4., 6., 8., 2., 6., 4., 2., 4., 2., 4.])

In [33]:
data[data%2==1]

array([1., 3., 5., 7., 9., 5., 7., 7., 3., 5., 3., 3., 5., 3., 1., 5., 3.,
       5., 3., 5., 3., 5.])

In [34]:
data[data==5]

array([5., 5., 5., 5., 5., 5., 5., 5.])

In [35]:
data

array([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [4., 5., 6., 7., 7., 8., 3., 5., 3.],
       [2., 3., 5., 6., 4., 3., 2., 1., 4.],
       [2., 4., 5., 3., 5., 3., 5., 3., 5.]])

In [40]:
# np.split(array_name, no_of_splits, axis)
# splits must be EQUAL

np.split(data,3,axis=1)

[array([[1., 2., 3.],
        [4., 5., 6.],
        [2., 3., 5.],
        [2., 4., 5.]]),
 array([[4., 5., 6.],
        [7., 7., 8.],
        [6., 4., 3.],
        [3., 5., 3.]]),
 array([[7., 8., 9.],
        [3., 5., 3.],
        [2., 1., 4.],
        [5., 3., 5.]])]

In [42]:
np.split(data,2,axis=0)

[array([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [4., 5., 6., 7., 7., 8., 3., 5., 3.]]),
 array([[2., 3., 5., 6., 4., 3., 2., 1., 4.],
        [2., 4., 5., 3., 5., 3., 5., 3., 5.]])]

In [44]:
# np.split(arr, [a,b], axis=0/1)   ---  arr[:a],arr[a:b],arr[b:]

np.split(data,[1,3], axis=0)     # [:1], [1:3], [3:]

[array([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 array([[4., 5., 6., 7., 7., 8., 3., 5., 3.],
        [2., 3., 5., 6., 4., 3., 2., 1., 4.]]),
 array([[2., 4., 5., 3., 5., 3., 5., 3., 5.]])]

In [46]:
np.split(data, [0,2], axis=0)

[array([], shape=(0, 9), dtype=float64),
 array([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [4., 5., 6., 7., 7., 8., 3., 5., 3.]]),
 array([[2., 3., 5., 6., 4., 3., 2., 1., 4.],
        [2., 4., 5., 3., 5., 3., 5., 3., 5.]])]

### comparing arrays

In [48]:
a=np.array([1,2,3])
b=np.array([2,4,3])

In [49]:
# Element wise comparison

np.equal(a,b)

array([False, False,  True])

In [50]:
# comparing full array

np.array_equal(a,b)

False

In [55]:
# Array Broadcasting
a=np.array([[1,2,3],[2,3,4],[4,5,6]])
b=np.array([[2,3,4]])


In [56]:
a

array([[1, 2, 3],
       [2, 3, 4],
       [4, 5, 6]])

In [57]:
b

array([[2, 3, 4]])

In [58]:
np.sum([a,b])

C:\Program Files\anaconda\lib\site-packages\numpy\core\fromnumeric.py:86: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)


array([[ 3,  5,  7],
       [ 4,  6,  8],
       [ 6,  8, 10]])

In [59]:
import warnings
warnings.filterwarnings("ignore")

In [60]:
np.sum([a,b])

array([[ 3,  5,  7],
       [ 4,  6,  8],
       [ 6,  8, 10]])