In [1]:
import numpy as np

In [34]:
arr1=np.array([[3,9,8],[6,5,7],[3,9,8]])
arr2=np.array([[3,9,8],[2,6,7],[3,5,7]])
arr3=np.array([[2,6,7],[6,5,7],[6,5,7]])

np.hstack([arr1,arr2])

array([[3, 9, 8, 3, 9, 8],
       [6, 5, 7, 2, 6, 7],
       [3, 9, 8, 3, 5, 7]])

In [14]:
a

array([['?', '?', '?', '?'],
       ['?', '?', '?', '?'],
       ['?', '?', '?', '?'],
       ['?', '?', '?', '?']], dtype='<U1')

In [4]:
type(a)

numpy.ndarray

In [36]:
# SLICING
arr1=np.array([[3,9,8,6],[1,6,5,7],[6,3,9,8]])
arr1
# ([ROW],[COLS])


array([[3, 9, 8, 6],
       [1, 6, 5, 7],
       [6, 3, 9, 8]])

In [37]:
print(arr1[[2,1,2],[0,1,3]])

[6 6 8]


In [40]:
arr1=np.array([[3,9,8,6,7],[1,6,5,7,5],[6,3,9,8,3],[1,6,5,7,5]])
arr1


array([[3, 9, 8, 6, 7],
       [1, 6, 5, 7, 5],
       [6, 3, 9, 8, 3],
       [1, 6, 5, 7, 5]])

In [39]:
print(arr1[1::2,:])

[[1 6 5 7 5]
 [1 6 5 7 5]]


In [41]:
np.matmul(arr1,arr2)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 5)

In [42]:
import pandas as pd


In [43]:
df=pd.DataFrame(d)

In [ ]:
d=pd.read_csv('hi.csv',